#!/bin/bash

echo "Pre-commit checks..."

FILES=$(go list ./... | grep -v /vendor/)

echo "go fmt\n"
go fmt ${FILES}

# Check all files for suspicious constructs
{
	go vet ${FILES}
} || {
	exitStatus=$?

	if [ $exitStatus ]; then
		printf "\ngo vet issues found in your code, please fix them and try again."
		exit 1
	fi
}

# Lint the entire project. Requires golint (https://github.com/golang/lint)
{
	golint ./...
} || {
	exitStatus=$?

	if [ $exitStatus ]; then
		printf "\nGoLint issues found in your code, please fix them and try again."
		exit 1
	fi
}

echo "Pre-commit checks successful!"
